spring:
  application:
    name: "SecureNotes"

  datasource:
    url: "jdbc:mysql://localhost:3306/securenotes"
    username: "root"
    password: "root"

  jpa:
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"

  security:
    user:
      name: "admin"
      password: "password"

  app:
    jwtSecret: "mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm"
    jwtExpirationMs: 172800000

logging:
  level:
    org:
      springframework:
        security: DEBUG
